name: cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build (${{ matrix.file.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - name: template_gba
            github: gamelly/core-native-gba
            command: docker run --rm -v $(pwd):/app -w /app devkitpro/devkitarm bash -c "cmake -Bbuild -H. && make -C build"
            artifact: build/bin/game.gba
          - name: cli_lua
            lua: true
            github: gamelly/gly-engine
            command: ./cli.sh cli-build
            artifact: dist/cli.lua
    steps:
      - 
        uses: actions/checkout@master
        with:
          repository: ${{ matrix.file.github }}
          ref: main
      -
        if: ${{ matrix.file.lua }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - 
        run: ${{ matrix.file.command }}
      -
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file.name }}-artifact
          path: ${{ matrix.file.artifact }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      -
        run: |
          mkdir -p dist
          find artifacts -type f -exec mv {} dist \;
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
      - 
        id: deployment
        uses: actions/deploy-pages@v2
