name: cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build (${{ matrix.file.name }})
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        file:
          - name: Cli Gly
            lua: true
            github: gamelly/gly-engine
            command: ./cli.sh cli-build
            artifact: dist/cli.lua
          - name: Cli Bundler
            lua: true
            github: gamelly/gly-engine
            command: lua tools/cd_lua_bundler.lua
            artifact: dist/bundler.lua
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.file.github }}
          ref: main
      - if: ${{ matrix.file.lua }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - run: ${{ matrix.file.command }}
      - if: ${{ matrix.file.command2 }}
        run: ${{ matrix.file.command2 }}
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: ${{ matrix.file.artifact }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
          path: dist
      - run: node index.js
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
