name: cd

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          repository: gamelly/gly-engine
          ref: main
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - 
        run: |
          ./cli.sh cli-build
      -
        uses: actions/configure-pages@v3
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      -
        id: deployment
        uses: actions/deploy-pages@v2
